coeus-impl/src/main/resources/org/kuali/coeus/propdev/impl/core/ProposalDocumentView.xml

OK, I think this is the right PR. Testing but the changes are correct.

KRACOEUS-8791: Adding copy info to header

---

coeus-impl/src/main/resources/org/kuali/coeus/propdev/impl/budget/core/ProposalBudgetHierarchySummary.xml

i guess i lost this file when i moved the PR to the kualico repo

KRACOEUS-8777:add missing hierarchybudgetsummary xml

---

coeus-impl/src/main/resources/META-INF/kc-config-defaults.xml
coeus-impl/src/main/resources/org/kuali/coeus/sys/impl/RiceBootstrapSpringBeans.xml
coeus-tool/src/main/config/userhome/kuali/main/dev/kc-config.xml.bundled.developer.template
coeus-tool/src/main/config/userhome/kuali/main/dev/kc-config.xml.embedded.developer.template
coeus-tool/src/main/config/userhome/kuali/main/dev/kc-config.xml.implementor.template

This change is dependent on https://github.com/KualiCo/kc-sql/pull/4. So make sure that is merged first.

KRACOEUS-8820 : Make flyway process configurable

---

coeus-impl/src/main/java/org/kuali/coeus/propdev/impl/person/ProposalPerson.java
coeus-impl/src/main/java/org/kuali/kra/institutionalproposal/service/impl/InstitutionalProposalServiceImpl.java
coeus-impl/src/main/resources/org/kuali/coeus/propdev/impl/core/ProposalPrintDialog.xml
coeus-impl/src/main/resources/org/kuali/coeus/propdev/impl/person/ProposalPerson.xml
coeus-impl/src/main/resources/org/kuali/coeus/propdev/impl/person/ProposalPersonnelPage.xml

only merge if we are certain the cx-kc6 environment is building the latest db from the kc-sql file, that contains the db changes need for this, the db changes are showing up locally so i assume the are also occuring on cx-kc6

KRACOEUS-6639:code changes for proposal person effort

---

coeus-impl/src/main/java/org/kuali/coeus/propdev/impl/specialreview/ProposalDevelopmentSpecialReviewController.java
coeus-impl/src/main/resources/org/kuali/coeus/propdev/impl/specialreview/ProposalCompliancePage.xml

Modals in Proposal Development Retain data even after they are closed
Validating modals in PD, only issue found in Compliance.
Reset compliance modal.

KRACOEUS-7942

---

coeus-impl/src/main/java/org/kuali/kra/coi/CoiDisclProject.java

KRACOEUS-8842
Fix issue - Missing parts of screen on report COI in New projects to disclose

KRACOEUS-8842

---

coeus-impl/src/main/java/org/kuali/coeus/common/budget/framework/personnel/BudgetPerson.java
coeus-impl/src/main/java/org/kuali/coeus/common/budget/framework/summary/BudgetSummaryService.java
coeus-impl/src/main/java/org/kuali/coeus/common/budget/impl/summary/BudgetSummaryServiceImpl.java
coeus-impl/src/main/java/org/kuali/coeus/propdev/impl/budget/core/ProposalBudgetRateAndPeriodController.java

KRACOEUS-8286
Fix to add new periods to person salary details when dates change in proposal
and default periods are triggered.

KRACOEUS-8286

---

coeus-impl/src/main/java/org/kuali/coeus/common/budget/impl/personnel/BudgetPersonnelBudgetServiceImpl.java
coeus-impl/src/main/java/org/kuali/coeus/propdev/impl/budget/nonpersonnel/ProposalBudgetPeriodProjectCostController.java

KRACOEUS-8176
Save new line items - budget personnel and non-personnel costs

KRACOEUS-8176

---

coeus-impl/src/main/java/org/kuali/coeus/propdev/impl/budget/subaward/PropDevPropDevBudgetSubAwardServiceImpl.java
coeus-impl/src/main/java/org/kuali/coeus/propdev/impl/budget/subaward/ProposalBudgetSubAwardController.java
coeus-impl/src/main/resources/org/kuali/coeus/propdev/impl/budget/subaward/ProposalBudgetSubawardsPage.xml

KRACOEUS-8802
Subaward - refresh dialog on delete and replace.
Also reset sub award period details on delete and replace.

KRACOEUS-8802: refresh dialog and reset sub award period details on delete and replace

---

coeus-impl/src/main/resources/org/kuali/coeus/propdev/impl/budget/core/ProposalBudgetSettings.xml

KRACOEUS-8805
Fix for budget Settings labels disappear when marked complete.

KRACOEUS-8805: Fix for budget Settings labels disappear when marked complete.

---

coeus-impl/src/main/resources/org/kuali/coeus/propdev/impl/person/ProposalPersonnelPage.xml

That's right, I got the 100th PR, wheeee!!! :)

KRACOEUS-8885: Removing notify from child proposals

---

coeus-impl/src/main/resources/org/kuali/coeus/propdev/impl/person/ProposalPersonnelPage.xml

Display unit and administrator details in Proposal personnel page

KRACOEUS-7453 Enable unit inquiry

---

coeus-impl/src/main/java/org/kuali/coeus/sys/framework/config/KcConfigurer.java
coeus-impl/src/main/java/org/kuali/coeus/sys/health/HealthCheckController.java
coeus-impl/src/main/resources/org/kuali/coeus/sys/impl/HealthCheckSpringBeans.xml
coeus-impl/src/main/resources/org/kuali/coeus/sys/impl/SysBootstrapSpringBeans.xml

Simple health check page that return 200 on success and 417 on failure.
Does simple query against the KC and Rice database to confirm they are accessible

KRACOEUS-8891:Health Check Page

---

coeus-impl/src/main/java/org/kuali/coeus/propdev/impl/attachment/ProposalDevelopmentAttachmentController.java
coeus-impl/src/main/java/org/kuali/coeus/propdev/impl/attachment/ProposalDevelopmentAttachmentHelper.java
coeus-impl/src/main/resources/org/kuali/coeus/propdev/impl/attachment/ProposalAttachmentsPage.xml

KRACOEUS-7451 Add status option for internal attachments
Include status option for add attachments and in the list.
Also add mark all status option.

KRACOEUS-7451 Add status option for internal attachments

---

coeus-impl/src/main/java/org/kuali/kra/award/web/struts/action/AwardAction.java
coeus-impl/src/main/java/org/kuali/kra/award/web/struts/action/AwardHomeAction.java

Distributable amount is incorrect only when editing amount via award screen.
Adjusting/setting both Obligated and Anticipated Distributable

KRACOEUS-8874 Incorrect distributable amount when editing amount in award

---

coeus-db/coeus-db-sql/src/main/resources/co/kuali/coeus/data/migration/sql/mysql/rice/demo/V601_022__fixing_sponsor_role_qualifiers.sql
coeus-impl/src/main/java/org/kuali/coeus/common/impl/sponsor/SponsorConstants.java
coeus-impl/src/main/java/org/kuali/coeus/common/impl/sponsor/SponsorMaintainableImpl.java
coeus-impl/src/main/java/org/kuali/coeus/common/impl/sponsor/SponsorMaintenanceDocumentRule.java

see commit messages for details

Kracoeus-8909: fixing several issues with sponsor

---

coeus-impl/src/main/java/org/kuali/coeus/propdev/impl/core/ProposalDevelopmentServiceImpl.java

Reverts KualiCo/kc#123
This change is causing significant performance problems for organizations with hundreds of units(367). It is so bad the proposal pages won't open at all. The original issue is now fixed by https://github.com/KualiCo/rice-kc/pull/5

Revert "KRACOEUS-8803 Fix unauthorized lead unit options"

---

coeus-impl/src/main/java/org/kuali/coeus/propdev/impl/budget/hierarchy/ProposalBudgetHierarchyServiceImpl.java
coeus-impl/src/main/java/org/kuali/coeus/propdev/impl/budget/modular/ProposalBudgetModularController.java

also fixed error when trying to sync a budget with modular periods.

KRACOEUS-8925:save budget on modular sync

---

coeus-db/coeus-db-data-conv/pom.xml
coeus-db/coeus-db-sql/pom.xml
coeus-db/coeus-db-xml/pom.xml
coeus-db/pom.xml
coeus-help/pom.xml
coeus-impl/pom.xml
coeus-impl/src/main/java/co/kuali/coeus/reporting/web/struts/action/ReportForwardAction.java
coeus-impl/src/main/java/org/kuali/coeus/sys/framework/controller/ServletRegistrator.java
coeus-impl/src/main/java/org/kuali/coeus/sys/framework/controller/interceptor/FilterRegistrator.java
coeus-impl/src/main/resources/META-INF/kc-config-defaults.xml
coeus-impl/src/main/resources/co/kuali/coeus/grm/impl/GrmRiceBootstrapSpringBeans.xml
coeus-impl/src/main/resources/co/kuali/coeus/grm/impl/GrmSysComponentSpringBeans.xml
coeus-impl/src/main/resources/org/kuali/coeus/sys/impl/RiceBootstrapSpringBeans.xml
coeus-impl/src/main/resources/org/kuali/coeus/sys/impl/SysComponentSpringBeans.xml
coeus-impl/src/main/resources/org/kuali/kra/CoreSpringBeans.xml
coeus-it/pom.xml
coeus-tool/pom.xml
coeus-webapp/pom.xml
coeus-webapp/src/main/resources/META-INF/kc-config-build.xml
coeus-webapp/src/main/webapp/WEB-INF/web.xml
pom.xml

* moved grm specific items to a profile (maven and spring)
* fixed several pom issue from code merge
* fixed the ReportAction that is clearly broken
* made all grm internal dependencies runtime scope so we do not have compile time dependencies
* confirmed app builds and starts with the grm profile enabled and disabled with the correct functionality

High Priority: KRACOEUS-8934: grm profile

---

coeus-impl/src/main/resources/META-INF/kc-config-defaults.xml
coeus-impl/src/main/resources/co/kuali/coeus/grm/impl/GrmRiceBootstrapSpringBeans.xml

This PR needs to be merged first:
https://github.com/KualiCo/kc-sql/pull/14

RESKC-193: supporting grm sql files

---

coeus-impl/src/main/java/org/kuali/coeus/propdev/impl/attachment/ProposalDevelopmentAttachmentController.java

This is a harmless fix but completes an important feature so I'd recommend merging to 6.0.1

KRACOEUS-8902: fix notification text

---

coeus-impl/src/main/java/org/kuali/coeus/propdev/impl/attachment/ProposalDevelopmentAttachmentController.java

RESKC-221:fix enroute attachment saving

---

coeus-impl/src/main/java/org/kuali/coeus/propdev/impl/budget/hierarchy/ProposalBudgetHierarchyServiceImpl.java

RESKC-215:fix STE on unlink hierarchy

---

coeus-db/coeus-db-sql/src/main/resources/co/kuali/coeus/data/migration/sql/mysql/kc/bootstrap/V602_001__RESKC-1.sql
coeus-db/coeus-db-sql/src/main/resources/co/kuali/coeus/data/migration/sql/oracle/kc/bootstrap/V602_001__RESKC-1.sql
coeus-impl/src/main/java/org/kuali/coeus/propdev/impl/budget/core/ProposalBudgetViewHelperServiceImpl.java
coeus-impl/src/main/java/org/kuali/coeus/propdev/impl/budget/subaward/BudgetSubAwards.java
coeus-impl/src/main/java/org/kuali/coeus/propdev/impl/budget/subaward/ProposalBudgetSubAwardController.java
coeus-impl/src/main/resources/org/kuali/coeus/propdev/impl/budget/subaward/ProposalBudgetSubawardsPage.xml

RESKC-1:fix subaward attachment data

---

coeus-db/coeus-db-sql/src/main/resources/co/kuali/coeus/data/migration/sql/mysql/kc/bootstrap/V602_002__RESKC-2.sql
coeus-db/coeus-db-sql/src/main/resources/co/kuali/coeus/data/migration/sql/oracle/kc/bootstrap/V602_002__RESKC-2.sql
coeus-impl/src/main/java/org/kuali/coeus/common/impl/attachment/KcAttachmentDataDaoImpl.java
coeus-impl/src/main/java/org/kuali/coeus/propdev/impl/attachment/Narrative.java
coeus-impl/src/main/java/org/kuali/coeus/propdev/impl/person/attachment/ProposalPersonBiography.java

Please merge https://github.com/KualiCo/kc/pull/169 before this one, do to db script version conflicts
fixes up https://github.com/KualiCo/kc/pull/166 a little bit

RESKC-2:fix attachment deletion on copy and hierarchy

---

coeus-impl/src/main/java/org/kuali/coeus/common/budget/impl/core/BudgetPersonnelCostElementValuesFinder.java
coeus-impl/src/main/java/org/kuali/coeus/common/budget/impl/core/CostElementValuesFinder.java
coeus-impl/src/main/java/org/kuali/coeus/propdev/impl/budget/nonpersonnel/BudgetNonPersonnelBudgetCategoryTypeValuesFinder.java
coeus-impl/src/main/java/org/kuali/coeus/propdev/impl/budget/nonpersonnel/BudgetNonPersonnelCategoryValuesFinder.java
coeus-impl/src/main/java/org/kuali/coeus/propdev/impl/budget/nonpersonnel/BudgetNonPersonnelCostElementValuesFinder.java
coeus-impl/src/main/resources/org/kuali/coeus/propdev/impl/budget/nonpersonnel/ProposalBudgetNonPersonnelCostsPage.xml

RESKC-9:added budget category to non-personnel add and edit modals

---

coeus-impl/src/main/java/org/kuali/coeus/common/impl/person/attr/KcPersonExtendedAttributesMaintenanceDocumentRule.java
coeus-impl/src/main/resources/org/kuali/coeus/common/impl/person/attr/PersonBiosketch.xml
coeus-impl/src/main/resources/org/kuali/coeus/common/impl/person/attr/PersonBiosketchMaintenanceDocument.xml

RESKC-222:fix biosketch validation on person extended attribute

---

coeus-impl/src/main/java/org/kuali/coeus/propdev/impl/basic/ProposalDevelopmentHomeController.java

RESKC-170:return authorization exception messaeg instead of STE

---

coeus-impl/src/main/resources/org/kuali/coeus/common/budget/impl/repository-budget.xml

Subawards are only used by prop dev and therefore only relevent under JPA

RESKC-233:Disable OJB mappings for subaward attachments

---

coeus-it/src/test/java/org/kuali/kra/test/OjbRepositoryMappingTest.java

In order to support configuring Jenkins CI test runs through Jenkins itself we need to be able to configure the OJB mapping test through system props

RESOPS-24:OJB mapping test configurable by system prop

---

coeus-impl/src/main/java/org/kuali/coeus/sys/impl/KcConfigVerifier.java

DO NOT MERGE UNTIL WE FIX OUR ENVIRONMENTS IN PUPPET.
I recently noticed that the instrumentation configuration is not present in any of our KualiCo environments.  EclipseLink requires instrumentation in order to use features like Lazy.
It used to be obvious when instrumentation was missing because a hard error would occur on application startup.  Then rice switched to static build-time instrumentation which made the error go away.  The error would show up relating to classloading the PersistableBusinessObjectBase class before it was instrumented.  Now that rice is doing static build-time instrumentation this isn't an issue.  What is still an issue is all of our JPA annotated classes.
I briefly looked into using static build time instrumentation but in order to do that you have to list …

RESKC-240: Verify that the Instrumentation Configuration is correct
